import { Router, type IRouter } from "express";
import healthRouter from "./health";
import statsRouter from "./stats";
import captainsRouter from "./captains";
import captainAssignmentsRouter from "./captain-assignments";
import commitmentsRouter from "./commitments";
import pledgesRouter from "./pledges";
import volunteersRouter from "./volunteers";
import captainPortalRouter from "./captain-portal";
import settingsRouter from "./settings";
import adminMigrateRouter from "./admin-migrate";
import meUpdateRouter from "./me-update";
import invoicesRouter from "./invoices";
import legacyConfirmRouter from "./legacy-confirm";
import paymentsRouter from "./payments";
import statementRouter from "./statement";
import bankTransactionsRouter from "./bank-transactions";
import communicationsRouter from "./communications";
import expensesRouter from "./expenses";

const router: IRouter = Router();

router.use(healthRouter);
router.use(statsRouter);
router.use(settingsRouter);
router.use(adminMigrateRouter);
router.use(captainsRouter);
router.use(captainAssignmentsRouter);
router.use(commitmentsRouter);
router.use(meUpdateRouter);
router.use(pledgesRouter);
router.use(invoicesRouter);
router.use(legacyConfirmRouter);
router.use(paymentsRouter);
router.use(statementRouter);
router.use(bankTransactionsRouter);
router.use(communicationsRouter);
router.use(expensesRouter);
router.use(volunteersRouter);
router.use(captainPortalRouter);

export default router;
